resources:
  - name: git-courier-resource
    type: git
    source:
      uri: https://github.com/github-patrick/courier-service
      branch: dockerfile


jobs:
  - name: courier-service-job
    public: true
    plan:
      - get: git-courier-resource
        trigger: true
      - task: hello-world
        config:
          platform: li nux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: ls
            args: [-laR]
  - name: build
    public: true
    plan:
      - get: git-courier-resource
        passed: [courier-service-job]
        trigger: true
      - task: build
        file: git-courier-resource/ci/tasks/build.yml
  - name: integration-tests
    public: true
    plan:
      - get: git-courier-resource
        passed: [build]
        trigger: true
      - task: integration
        file: git-courier-resource/ci/tasks/integration-tests.yml
