platform: linux
image_resource:
  type: docker-image
  source:
    repository: zenika/alpine-maven
    tag: 3-jdk8

inputs:
  - name: git-courier-resource

caches:
  - path: git-courier-resource/.m2

run:
  path: git-courier-resource/ci/scripts/build.sh