platform: linux
image_resource:
  type: docker-image
  source: {repository: dockerdozens/maven-dind-alpine}

inputs:
  - name: git-courier-resource
    
run:
  path: git-courier-resource/ci/scripts/build.sh