resources:
  - name: git-courier-resource
    type: git
    source:
      uri: https://github.com/github-patrick/courier-service
      branch: dockerfile


jobs:
  - name: courier-service-job
    public: true
    plan:
      - get: git-courier-resource
        trigger: true
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: ls
            args: [-laR]
  - name: build-test
    public: true
    plan:
      - get: git-courier-resource
        passed: [courier-service-job]
        trigger: true
      - task: build and test
#        file: git-courier-resource/ci/tasks/build-test.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: dockerdozens/maven-dind-alpine}
          run:
            path: mvn
            args: [clean]
